### ISSUE TITLE
Add Error assertions

### ISSUE THREAD

**Issue by remcowesterhoud** [camunda-cloud/camunda-cloud-testing#12]
**Description**

We would like to have assertions that enable us to assert specific conditions of an Error. Examples of some assertions could be:

- Error has been thrown
- Error was handles by the process
- Error was escalated to an incident

**Comment by pihme** [comment]
Not sure what we can do here. 

Errors are thrown by a job. The error either activates an catch error event element or it raises an incident

> *  Error has been thrown

I don't think this needs to be tested, because the only way an error is thrown is within the test itself

> * Error was handles by the process

Not sure we need a special assertion here, as we can just check whether the catch error event element has been activated, so it is equivalent to `assertThat(processInstance).hasPassed(catchErrorElementId)`

> *  Error was escalated to an incident
Not sure we need a special assertion here. is equivalent to `assrtThat(job).hasAnyIncidents()` 

Overall, I suggest to wait for user feedback if need special assertions for errors.

**Comment by remcowesterhoud** [comment]
In that case lets close this for now. Once we receive feedback we can create a new issue that is more specific than this one is.
